language: python
python:
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install codecov
script:
  - pytest --cov=./
env:
  - CODECOV_TOKEN=f27128dd-b5a8-4e74-b0a5-1eded2522a74
after_success:
    - codecov